Indentation.
Signed-off-by: Oliver Freyermuth <o.freyermuth@googlemail.com>

diff --git a/dockerhub2oci b/dockerhub2oci
--- a/dockerhub2oci
+++ b/dockerhub2oci
@@ -42,14 +42,14 @@ if [ $? != 0 ] ; then printHelp; exit 1; fi
 eval set -- "$TEMP"
 while true ; do
 	case "$1" in
-		--repo)     repo=$2;     shift 2;;
-		--image)    image=$2;    shift 2;;
-		--tag)      tag=$2;      shift 2;;
-		--cachedir) cachedir=$2; shift 2;;
+		--repo)          repo=$2;            shift 2;;
+		--image)         image=$2;           shift 2;;
+		--tag)           tag=$2;             shift 2;;
+		--cachedir)      cachedir=$2;        shift 2;;
 		--writable-dirs) writable_dirs=true; shift 1;;
-		-h|--help)  help;        exit 0;;
-		--)         shift;       break;;
-		*) echo "Internal error!"; exit 1;;
+		-h|--help)       help;               exit 0;;
+		--)              shift;              break;;
+		*) echo "Internal error!";           exit 1;;
 	esac
 done
 
@@ -122,8 +122,8 @@ for HASHLAYER in ${layers}; do
 	fi
 
 	tar --overwrite --exclude=dev/* -C ${imgroot} -xf ${cachedir}/${HASHLAYER}.tar.gz
-        if $writable_dirs; then
-                # make sure all directories are owner-writable
-                find ${imgroot} -type d ! -perm -200 -print0|xargs -0 -r chmod u+w
-        fi
+	if ${writable_dirs}; then
+		# make sure all directories are owner-writable
+		find ${imgroot} -type d ! -perm -200 -print0|xargs -0 -r chmod u+w
+	fi
 done
