updating scripts to have functions

diff --git a/dockerhub2oci b/dockerhub2oci
--- a/dockerhub2oci
+++ b/dockerhub2oci
@@ -28,7 +28,17 @@ EOF
 exit 1
 }
 
+# Ensure functions available
+
+HERE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+
+if [ ! -f "${HERE}/blob2oci" ]; then
+    echo "Cannot find blob2oci, exiting."
+    exit 1 
+fi
+
 # Defaults
+
 registry="registry.hub.docker.com"
 repo="gliderlabs"
 image="alpine"
@@ -43,8 +53,7 @@ if [ $? != 0 ] ; then printHelp; exit 1; fi
 eval set -- "$TEMP"
 while true ; do
 	case "$1" in
-        	--repo)          repo=$2;            shift 2;;
-                --registry)      registry=$2;        shift 2;;
+		--repo)          repo=$2;            shift 2;;
 		--image)         image=$2;           shift 2;;
 		--tag)           tag=$2;             shift 2;;
 		--cachedir)      cachedir=$2;        shift 2;;
@@ -64,15 +73,8 @@ mkdir -p ${imgroot}
 
 img_full="${repo}/${image}"
 
-# Support for nvidia or other (Docker Hub)
-
-if [ "${registry}" == "nvcr.io" ]; then
-    auth_uri="https://authn.nvidia.com/token"
-    auth_uri_full="${auth_uri}?service=registry&scope=repository:${img_full}:pull"
-else
-    auth_uri="https://auth.docker.io/token"
-    auth_uri_full="${auth_uri}?service=registry.docker.io&scope=repository:${img_full}:pull"
-fi
+auth_uri="https://auth.docker.io/token"
+auth_uri_full="${auth_uri}?service=registry.docker.io&scope=repository:${img_full}:pull"
 
 reg_uri_manifest="https://${registry}/v2/${img_full}/manifests/${tag}"
 reg_uri_blobs="https://${registry}/v2/${img_full}/blobs"
@@ -102,49 +104,8 @@ for HASHLAYER in ${layers_dl}; do
 done | aria2c -i - -d ${cachedir} --header="Authorization: Bearer ${token}" -V
 
 for HASHLAYER in ${layers}; do
-	# Whiteout handling.
-	whiteouts_unchecked=$(tar tf ${cachedir}/${HASHLAYER}.tar.gz --wildcards --wildcards-match-slash ".wh..wh..opq" "*/.wh..wh..opq" ".wh.*" "*/.wh.*" 2>/dev/null)
 
-	# Safety: Check for filenames with newline.
-	num_bad_whiteouts=$(echo -n "${whiteouts_unchecked}" | grep -v '.wh.' | wc -l)
-	if [ ! ${num_bad_whiteouts} -eq 0 ]; then
-		echo "There are ${num_bad_whiteouts} whiteout files with newline characters in the filename in layer ${HASHLAYER}:"
-		echo "${whiteouts_unchecked}" | grep -v '.wh.'
-		echo "This is likely malicious content, exiting now!"
-		exit 1
-	fi
+        # Call blob2oci to handle the layer
+        exec "${HERE}/blob2oci" --layer "$layer" --extract "${imgroot}" --writable-dirs ${writable_dirs}
 
-	whiteouts=$(echo "${whiteouts_unchecked}" | tr '\n' '\0' | xxd -p)
-
-	opaque_whiteouts=$(echo -n "${whiteouts}" | xxd -p -r | grep -ze '\.wh\.\.wh\.\.opq$' | xxd -p)
-	explicit_whiteouts=$(echo -n "${whiteouts}" | xxd -p -r | grep -zve '\.wh\.\.wh\.\.opq$' | grep -ze '\.wh\.[^/]\+$' | xxd -p)
-
-	if [ ! -z "${opaque_whiteouts}" ]; then
-		echo "Warning: Layer ${HASHLAYER} contains opaque whiteout files:"
-		while IFS= read -r -d '' whiteout_file; do
-			echo "${whiteout_file}"
-		done < <(echo -n "${opaque_whiteouts}" | xxd -p -r)
-		echo "We do not handle these yet!"
-	fi
-	if [ ! -z "${explicit_whiteouts}" ]; then
-		while IFS= read -r -d '' whiteout_file; do
-			to_be_deleted=${imgroot}/$(echo "${whiteout_file}" | sed 's#\.wh\.\([^/]\+\)$#\1#')
-			# Ensure this is below our tree
-			case $(readlink -f "${to_be_deleted}") in
-				$(readlink -f .)/*)
-					rm -rf "${to_be_deleted}";;
-				*)
-					echo "ERROR!";
-					echo "File ${to_be_deleted} is not below extracted tree!";
-					echo "This looks malicious, exiting now!";
-					exit 1;;
-			esac
-		done < <(echo -n "${explicit_whiteouts}" | xxd -p -r)
-	fi
-	tar --overwrite --exclude=dev/* --exclude=*/.wh.* -C ${imgroot} -xf ${cachedir}/${HASHLAYER}.tar.gz
-	if ${writable_dirs}; then
-		# make sure all directories are owner-writable
-		find ${imgroot} -type d ! -perm -200 -print0|xargs -0 -r chmod u+w
-	fi
 done
-
